# Site settings
title: Emil Smith
email: me@emilsmoothwall.com
description: My website I suppose
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
download_button_url: https://google.com

# Social settings
facebook_url:
github_url: https://github.com/smithomaster
instagram_url:

# Build settings
markdown: kramdown
